129 Refactored integration-tests
exasol/dynamodb-virtual-schema pull request #151
Opened 2020-11-24 09:01 UTC by jakobbraun

Closes #129

2020-11-27 14:02 UTC, morazow requested changes

2020-11-30 14:26 UTC, jakobbraun commented on src/test/java/com/exasol/dynamodb/DynamodbContainer.java
> +     * @return port dynamodb is maped to
```suggestion
     * @return port DynamoDB is mapped to
```

2020-11-30 14:27 UTC, jakobbraun commented on src/main/java/com/exasol/dynamodb/DynamodbConnectionFactory.java
> +            throw new IllegalArgumentException(ExaError.messageBuilder("E-VSDY-1")
no. dynamodb virtual schema has vsdy. vsd is virtual-schema-common-document

2020-11-30 15:23 UTC, morazow approved these changes
Remove the fixed oss-index vulnerability, then good to merge!

2020-11-30 15:23 UTC, morazow commented on pom.xml
> +                </configuration>
Now, this is fixed, I think you can also remove it here.

2021-01-11 10:30 UTC, merged